# TypeError: 'list' object is not callable



Version: Python 3.8.3



파이썬에서 일어나는 에러중

TypeError: 'list' object is not callable



![image-20201014090157659](C:\Users\won\AppData\Roaming\Typora\typora-user-images\image-20201014090157659.png)







![image-20201014091027048](C:\Users\won\AppData\Roaming\Typora\typora-user-images\image-20201014091027048.png)





